Training with a single process on 1 GPUs.
Model CSWin_64_12211_tiny_224 created, param count: 21809604
Data processing configuration for current model + dataset:
	input_size: (3, 224, 224)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.9
Loaded state_dict_ema from checkpoint '/home/gcperkins/CSWin-Transformer/cswin_tiny_224.pth'
/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/apex/__init__.py:68: DeprecatedFeatureWarning: apex.amp is deprecated and will be removed by the end of February 2023. Use [PyTorch AMP](https://pytorch.org/docs/stable/amp.html)
  warnings.warn(msg, DeprecatedFeatureWarning)
Using NVIDIA APEX AMP. Training in mixed precision.
Scheduled epochs: 1025
/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torchvision/transforms/transforms.py:330: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torchvision/transforms/functional.py:443: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
Traceback (most recent call last):
  File "finetune.py", line 1021, in <module>
    main()
  File "finetune.py", line 729, in main
    amp_autocast=amp_autocast, loss_scaler=loss_scaler, model_ema=model_ema, mixup_fn=mixup_fn)
  File "finetune.py", line 920, in train_epoch
    100. * batch_idx / last_idx,
ZeroDivisionError: float division by zero
/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/launch.py:188: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 698785) of binary: /home/gcperkins/miniconda3/envs/cswin/bin/python
Traceback (most recent call last):
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
    )(*cmd_args)
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gcperkins/miniconda3/envs/cswin/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-23_15:30:32
  host      : emmanuel-01.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 698785)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
